 <?php

return [
    'base_url' => 'https://www.castaneas.fr',
    'payment_simulate' => false,
    'up2pay' => [
        'site' => '1234567',
        'rang' => '01',
        'identifiant' => '123456789',
        'hmac_key' => 'VOTRE_CLE_HMAC',
        'callback_secret' => 'UN_SECRET_LONG_POUR_PAYMENT_NOTIFY',
        'gateway_url' => 'https://tpeweb.e-transactions.fr/php/',
        'currency' => '978',
        'language' => 'FRA',
        'hash_algo' => 'SHA512',
    ],
    'paypal' => [
        'client_id' => 'VOTRE_PAYPAL_CLIENT_ID',
        'secret' => 'VOTRE_PAYPAL_SECRET',
        'base_url' => 'https://api-m.sandbox.paypal.com',
        'currency' => 'EUR',
        'brand_name' => 'Castaneas',
        'locale' => 'fr-FR',
        'webhook_id' => 'VOTRE_PAYPAL_WEBHOOK_ID',
        'ca_bundle' => '',
        'skip_ssl_verify' => false,
    ],
    'sucrine' => [
        'api_key' => 'VOTRE_CLE_API_SUCRINE',
        'base_url' => 'https://app.sucrine.club/api',
        'catalogue_id' => 'ID_DU_CATALOGUE_SUCRINE',
        'order_source' => 'castaneas',
        'skip_precise_supply_check' => true,
        'delivery_vat_rate' => 20,
        'ca_bundle' => '',
        'skip_ssl_verify' => false,
        'delivery_point' => '',
    ],
    'sendcloud' => [
        'public_key' => 'VOTRE_CLE_PUBLIQUE_SENDCLOUD',
        'secret_key' => 'VOTRE_CLE_PRIVEE_SENDCLOUD',
        'base_url' => 'https://panel.sendcloud.sc/api/v2',
        'sender_address' => '',
        'ca_bundle' => '',
        'skip_ssl_verify' => false,
        'shipping_method_id' => '',
        'shipping_method_name' => '',
        'request_label' => true,
        'apply_shipping_rules' => true,
    ],
    'google_places' => [
        'api_key' => 'VOTRE_CLE_API_GOOGLE_PLACES',
        'base_url' => 'https://places.googleapis.com/v1',
        'place_id' => '',
        'query' => 'CASTANÉAS Albias',
        'language' => 'fr',
        'region' => 'FR',
        'ca_bundle' => '',
        'skip_ssl_verify' => false,
    ],
];